In [1]:
import pandas as pd

## Reading Data

In [2]:
df = pd.read_csv('data.csv')

In [3]:
df.head()

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
0   99.797377         0   88          1           0             -1
1   98.064516         1   47          1           1             -1
2   98.661425         1   35          0           1             -1
3  101.467446         1   13          0           0             -1
4   98.825403         1   37          1           0             -1

In [4]:
df.tail()

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
2570  98.688671         0   97          1           0             -1
2571  98.434244         1   56          1           1              0
2572  98.524078         0   21          1           0              0
2573  99.777101         0   10          1           0             -1
2574  99.852662         1   94          1           0              0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2575 entries, 0 to 2574
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   fever          2575 non-null   float64
 1   bodyPain       2575 non-null   int64  
 2   age            2575 non-null   int64  
 3   runnyNose      2575 non-null   int64  
 4   diffBreath     2575 non-null   int64  
 5   infectionProb  2575 non-null   int64  
dtypes: float64(1), int64(5)
memory usage: 120.8 KB


## Train Test Spliting

In [6]:
import numpy as np

In [15]:
def data_split(data, ratio):
    np.random.seed(42)
    shuffled = np.random.permutation(len(data))
    test_set_size = int(len(data) * ratio)
    test_indices = shuffled[:test_set_size]
    train_indices = shuffled[test_set_size:]
    return data.iloc[train_indices], data.iloc[test_indices]

In [16]:
train, test = data_split(df, 0.2)

In [17]:
train

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
1703   98.716879         0   57          0           0              0
1675   99.921020         1   83          0           1              0
1518   98.037677         0  100          0           0             -1
361   101.609801         0   10          1           1              0
1544  100.038029         1   68          1           0             -1
...          ...       ...  ...        ...         ...            ...
1638  100.995756         0   29          0           0             -1
1095  101.418055         0   49          0           1             -1
1130  100.989973         1   35          1           0             -1
1294  100.124469         0   98          1           0             -1
860   100.348835         1   62          1           0              0

[2060 rows x 6 columns]

In [18]:
test

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
1644   99.988398         1   45          0           0              0
1189   98.744903         1   63          1           1             -1
495   101.916788         0    6          0           0             -1
1656   98.207894         1   60          0           0              0
651   101.145019         0    2          0           0             -1
...          ...       ...  ...        ...         ...            ...
1627  101.334915         1    8          1           1              0
471   100.499929         1   79          1           1             -1
700    98.960013         0   20          1           0             -1
25    100.263159         1   50          1           0              0
755    98.091983         0   52          1           1             -1

[515 rows x 6 columns]

In [36]:
X_train = train[['fever', 'bodyPain', 'age', 'runnyNose', 'diffBreath']].to_numpy()
X_test = test[['fever', 'bodyPain', 'age', 'runnyNose', 'diffBreath']].to_numpy()

In [27]:
x_train

array([[ 98.71687919,   0.        ,  57.        ,   0.        ,
          0.        ],
       [ 99.92102016,   1.        ,  83.        ,   0.        ,
          1.        ],
       [ 98.03767689,   0.        , 100.        ,   0.        ,
          0.        ],
       ...,
       [100.9899726 ,   1.        ,  35.        ,   1.        ,
          0.        ],
       [100.1244688 ,   0.        ,  98.        ,   1.        ,
          0.        ],
       [100.3488346 ,   1.        ,  62.        ,   1.        ,
          0.        ]])

In [40]:
Y_train = train[['infectionProb']].to_numpy().reshape(2060 , )
Y_test = test[['infectionProb']].to_numpy().reshape(515 , )

In [39]:
Y_train

array([ 0,  0, -1, ..., -1, -1,  0], dtype=int64)

In [31]:
Y_train

array([[ 0,  0, -1, ..., -1, -1,  0]], dtype=int64)

In [41]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()
clf.fit(X_train, Y_train)

LogisticRegression()

In [46]:
inputFeatures = [100, 1, 22, 1, 1]
infProb = clf.predict_proba([inputFeatures])[0][1]

In [47]:
infProb

0.4684188139267936

In [48]:
inputFeatures

[100, 1, 22, 1, 1]

In [49]:
infProb

0.4684188139267936